# Generated by Django 2.2.6 on 2019-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254)),
                ('upwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.CharField(max_length=50)),
                ('uemail', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=100)),
                ('exname', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('stripetoken', models.TextField()),
                ('charge_response', models.TextField()),
            ],
            options={
                'db_table': 'user_exams',
            },
        ),
    ]
